name: Build, Test, and Push to GHCR

on:
  push:
    branches: [ "main", "master" ]
  pull_request:

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repo
      - name: Check out the code
        uses: actions/checkout@v3

      # 2) Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      # 3) Build and test with Maven
      - name: Build and Test
        run: mvn clean install

      # 4) Log in to GHCR
      #    Use the automatically provided GITHUB_TOKEN to authenticate to ghcr.io
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      # 5) Build the Docker image
      - name: Build Docker Image
        run: |
          # Use the GitHub repository owner and name to construct the image name
          IMAGE_NAME=ghcr.io/${{ github.repository }}/spring-boot-demo:latest
          echo "IMAGE_NAME=$IMAGE_NAME"
          docker build -t $IMAGE_NAME .

      # 6) Push the Docker image to GHCR
      - name: Push Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/spring-boot-demo:latest
          docker push $IMAGE_NAME
